version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: search_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: search_engine
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: search_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/search_engine
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: